const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REACTION = "NEW_REACTION";
const MESSAGE_READ = "MESSAGE_READ";
const NEW_READ_RECEIPT = "NEW_READ_RECEIPT";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";
const USER_SET_STATUS = "USER_SET_STATUS";
const USER_STATUS_UPDATED = "USER_STATUS_UPDATED";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  NEW_REACTION,
  MESSAGE_READ,
  NEW_READ_RECEIPT,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  USER_SET_STATUS,
  USER_STATUS_UPDATED,
};